In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Table01.csv') #讀取資料

In [4]:
df.head() # check top5 rows

,時間(月),行業,每人每月薪資,經常性\n薪資,非經常性薪資,加班費,平均\n工時,正常\n工時,加班\n工時,進\n入\n率,退\n出\n率,薪資\n指數,經常性\n薪資\n指數
0,86/1,工業及服務業,21790,240,21550,37,-,-0.1,0.1,0.15,0.34,47.88,0.65
1,86/2,工業及服務業,-8965,-818,-8147,-198,-41.8,-40.3,-1.5,-0.21,0.19,-19.70,-2.23
2,86/3,工業及服務業,-14757,908,-15665,244,40.3,38.7,1.6,1.19,-0.02,-32.43,2.48
3,86/4,工業及服務業,217,178,39,-18,-2.4,-2.4,-,-0.46,-0.13,0.48,0.48
4,86/5,工業及服務業,334,129,205,-40,9.5,9.8,-0.3,0.13,0.05,0.73,0.35

In [5]:
df.drop(df.columns[[0, 1]], axis=1, inplace=True) # drop first 2 columns, not needed

In [6]:
df

,每人每月薪資,經常性\n薪資,非經常性薪資,加班費,平均\n工時,正常\n工時,加班\n工時,進\n入\n率,退\n出\n率,薪資\n指數,經常性\n薪資\n指數
0,21790,240,21550,37,-,-0.1,0.1,0.15,0.34,47.88,0.65
1,-8965,-818,-8147,-198,-41.8,-40.3,-1.5,-0.21,0.19,-19.70,-2.23
2,-14757,908,-15665,244,40.3,38.7,1.6,1.19,-0.02,-32.43,2.48
3,217,178,39,-18,-2.4,-2.4,-,-0.46,-0.13,0.48,0.48
4,334,129,205,-40,9.5,9.8,-0.3,0.13,0.05,0.73,0.35
...,...,...,...,...,...,...,...,...,...,...,...
235,-1206,113,-1319,-46,15.2,15.4,-0.2,-0.22,0.16,-2.65,0.31
236,-508,-183,-325,1,-23.3,-23.2,-0.1,-0.08,0.08,-1.12,-0.50
237,-2136,227,-2363,275,-1.5,-3.0,1.5,-0.27,-0.43,-4.69,0.62
238,807,102,705,-41,16.0,16.4,-0.4,-0.26,-0.34,1.77,0.27
239,3852,265,3587,-36,-0.1,0.1,-0.2,-0.19,-0.13,8.47,0.73

In [7]:
df.isnull().sum() # check nan

每人每月薪資         0
經常性\n薪資        0
非經常性薪資         0
加班費            0
平均\n工時         0
正常\n工時         0
加班\n工時         0
進\n入\n率        0
退\n出\n率        0
薪資\n指數         0
經常性\n薪資\n指數    0
dtype: int64

In [8]:
df= df.replace('-', 0) # 用0補值，每筆data是和前個月相差， - 表示兩月數值相同，無變動

In [9]:
df

,每人每月薪資,經常性\n薪資,非經常性薪資,加班費,平均\n工時,正常\n工時,加班\n工時,進\n入\n率,退\n出\n率,薪資\n指數,經常性\n薪資\n指數
0,21790,240,21550,37,0,-0.1,0.1,0.15,0.34,47.88,0.65
1,-8965,-818,-8147,-198,-41.8,-40.3,-1.5,-0.21,0.19,-19.70,-2.23
2,-14757,908,-15665,244,40.3,38.7,1.6,1.19,-0.02,-32.43,2.48
3,217,178,39,-18,-2.4,-2.4,0,-0.46,-0.13,0.48,0.48
4,334,129,205,-40,9.5,9.8,-0.3,0.13,0.05,0.73,0.35
...,...,...,...,...,...,...,...,...,...,...,...
235,-1206,113,-1319,-46,15.2,15.4,-0.2,-0.22,0.16,-2.65,0.31
236,-508,-183,-325,1,-23.3,-23.2,-0.1,-0.08,0.08,-1.12,-0.50
237,-2136,227,-2363,275,-1.5,-3.0,1.5,-0.27,-0.43,-4.69,0.62
238,807,102,705,-41,16.0,16.4,-0.4,-0.26,-0.34,1.77,0.27
239,3852,265,3587,-36,-0.1,0.1,-0.2,-0.19,-0.13,8.47,0.73

In [8]:
df.dtypes #check dtypes

每人每月薪資           int64
經常性\n薪資         object
非經常性薪資           int64
加班費             object
平均\n工時          object
正常\n工時         float64
加班\n工時          object
進\n入\n率         object
退\n出\n率        float64
薪資\n指數         float64
經常性\n薪資\n指數     object
dtype: object

In [9]:
df= df.astype(float) # convert to float

In [10]:
df.dtypes

每人每月薪資         float64
經常性\n薪資        float64
非經常性薪資         float64
加班費            float64
平均\n工時         float64
正常\n工時         float64
加班\n工時         float64
進\n入\n率        float64
退\n出\n率        float64
薪資\n指數         float64
經常性\n薪資\n指數    float64
dtype: object

In [11]:
# rename columns
df.columns = ['salary', 'recurring','non_recurring','overtime_pay','average_hour','normal_hour','overtime_hour','enter','exit','wage_index','recurring_index']

In [12]:
df.describe()

,salary,recurring,non_recurring,overtime_pay,average_hour,normal_hour,overtime_hour,enter,exit,wage_index,recurring_index
count,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000
mean,47.004167,38.629167,8.375000,1.200000,-0.089167,-0.084583,-0.004583,0.000042,-0.000375,0.103542,0.105292
std,12696.719105,303.065689,12725.568988,78.255573,18.433573,18.111728,0.539118,0.383801,0.292156,27.899090,0.825852
min,-46534.000000,-1110.000000,-46130.000000,-314.000000,-52.800000,-51.500000,-2.000000,-0.770000,-0.760000,-102.200000,-3.030000
25%,-856.000000,-61.500000,-934.750000,-40.000000,-8.375000,-8.350000,-0.300000,-0.270000,-0.212500,-1.885000,-0.172500
50%,106.000000,54.000000,59.500000,-2.000000,-1.050000,-0.850000,0.000000,-0.080000,0.040000,0.235000,0.150000
75%,1227.000000,160.500000,1227.500000,37.250000,8.925000,9.000000,0.200000,0.152500,0.212500,2.697500,0.440000
max,41955.000000,984.000000,41839.000000,275.000000,55.100000,54.000000,1.700000,1.220000,0.700000,92.190000,2.680000

In [13]:
#1. ============================================================================

In [14]:
y = df['exit'] 
X = df.loc[:, df.columns != 'exit']

In [15]:
import statsmodels.api as sm
X = sm.add_constant(X)   #增加模型的常數

model0 = sm.OLS(y,X)    #OLS
results0 = model0.fit() #fitting

print(results0.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   exit   R-squared:                       0.404
Model:                            OLS   Adj. R-squared:                  0.383
Method:                 Least Squares   F-statistic:                     19.57
Date:                Wed, 12 Oct 2022   Prob (F-statistic):           2.05e-22
Time:                        22:14:18   Log-Likelihood:                 17.362
No. Observations:                 240   AIC:                            -16.72
Df Residuals:                     231   BIC:                             14.60
Df Model:                           8
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.0066      0.015      0.430      0.668      -0.024       0.037
salary              0.0044      0.006      0.789      0.431      -0.007       0.016
recurring           0.0057      0.008      0.731      0.466      -0.010       0.021
non_recurring      -0.0013      0.004     -0.301      0.764      -0.010       0.007
overtime_pay       -0.0005      0.001     -0.666      0.506      -0.002       0.001
average_hour       -0.0038      0.037     -0.101      0.920      -0.078       0.070
normal_hour         0.0021      0.038      0.056      0.955      -0.072       0.076
overtime_hour      -0.0059      0.075     -0.079      0.937      -0.154       0.142
enter               0.5326      0.047     11.264      0.000       0.439       0.626
wage_index         -1.4293      2.830     -0.505      0.614      -7.005       4.146
recurring_index    -2.6343      4.154     -0.634      0.527     -10.819       5.551
==============================================================================
Omnibus:                        6.422   Durbin-Watson:                   2.181
Prob(Omnibus):                  0.040   Jarque-Bera (JB):                6.134
Skew:                           0.356   Prob(JB):                       0.0466
Kurtosis:                       3.327   Cond. No.                     1.36e+19
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.19e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [16]:
#2================================================================================================
y = df['exit'] 
X = df.loc[:, df.columns != 'exit']

In [17]:
X

,salary,recurring,non_recurring,overtime_pay,average_hour,normal_hour,overtime_hour,enter,wage_index,recurring_index
0,21790.0,240.0,21550.0,37.0,0.0,-0.1,0.1,0.15,47.88,0.65
1,-8965.0,-818.0,-8147.0,-198.0,-41.8,-40.3,-1.5,-0.21,-19.70,-2.23
2,-14757.0,908.0,-15665.0,244.0,40.3,38.7,1.6,1.19,-32.43,2.48
3,217.0,178.0,39.0,-18.0,-2.4,-2.4,0.0,-0.46,0.48,0.48
4,334.0,129.0,205.0,-40.0,9.5,9.8,-0.3,0.13,0.73,0.35
...,...,...,...,...,...,...,...,...,...,...
235,-1206.0,113.0,-1319.0,-46.0,15.2,15.4,-0.2,-0.22,-2.65,0.31
236,-508.0,-183.0,-325.0,1.0,-23.3,-23.2,-0.1,-0.08,-1.12,-0.50
237,-2136.0,227.0,-2363.0,275.0,-1.5,-3.0,1.5,-0.27,-4.69,0.62
238,807.0,102.0,705.0,-41.0,16.0,16.4,-0.4,-0.26,1.77,0.27
239,3852.0,265.0,3587.0,-36.0,-0.1,0.1,-0.2,-0.19,8.47,0.73

In [18]:
# 可明顯看出 salary 由 recurring+non_recurring 所構成，三者存在共線性。故刪除salary 欄位

X.drop(X.columns[[0]], axis=1, inplace=True)

C:\Users\James\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [19]:
X

,recurring,non_recurring,overtime_pay,average_hour,normal_hour,overtime_hour,enter,wage_index,recurring_index
0,240.0,21550.0,37.0,0.0,-0.1,0.1,0.15,47.88,0.65
1,-818.0,-8147.0,-198.0,-41.8,-40.3,-1.5,-0.21,-19.70,-2.23
2,908.0,-15665.0,244.0,40.3,38.7,1.6,1.19,-32.43,2.48
3,178.0,39.0,-18.0,-2.4,-2.4,0.0,-0.46,0.48,0.48
4,129.0,205.0,-40.0,9.5,9.8,-0.3,0.13,0.73,0.35
...,...,...,...,...,...,...,...,...,...
235,113.0,-1319.0,-46.0,15.2,15.4,-0.2,-0.22,-2.65,0.31
236,-183.0,-325.0,1.0,-23.3,-23.2,-0.1,-0.08,-1.12,-0.50
237,227.0,-2363.0,275.0,-1.5,-3.0,1.5,-0.27,-4.69,0.62
238,102.0,705.0,-41.0,16.0,16.4,-0.4,-0.26,1.77,0.27
239,265.0,3587.0,-36.0,-0.1,0.1,-0.2,-0.19,8.47,0.73

In [20]:
# 工時 = 正常工時 + 加班 ! 也存在共線性
X.drop(X.columns[[3]], axis=1, inplace=True)

C:\Users\James\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [21]:
X

,recurring,non_recurring,overtime_pay,normal_hour,overtime_hour,enter,wage_index,recurring_index
0,240.0,21550.0,37.0,-0.1,0.1,0.15,47.88,0.65
1,-818.0,-8147.0,-198.0,-40.3,-1.5,-0.21,-19.70,-2.23
2,908.0,-15665.0,244.0,38.7,1.6,1.19,-32.43,2.48
3,178.0,39.0,-18.0,-2.4,0.0,-0.46,0.48,0.48
4,129.0,205.0,-40.0,9.8,-0.3,0.13,0.73,0.35
...,...,...,...,...,...,...,...,...
235,113.0,-1319.0,-46.0,15.4,-0.2,-0.22,-2.65,0.31
236,-183.0,-325.0,1.0,-23.2,-0.1,-0.08,-1.12,-0.50
237,227.0,-2363.0,275.0,-3.0,1.5,-0.27,-4.69,0.62
238,102.0,705.0,-41.0,16.4,-0.4,-0.26,1.77,0.27
239,265.0,3587.0,-36.0,0.1,-0.2,-0.19,8.47,0.73

In [22]:
X.drop(X.columns[[6,7]], axis=1, inplace=True)

C:\Users\James\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [23]:
X

     recurring  non_recurring  overtime_pay  normal_hour  overtime_hour  enter
0        240.0        21550.0          37.0         -0.1            0.1   0.15
1       -818.0        -8147.0        -198.0        -40.3           -1.5  -0.21
2        908.0       -15665.0         244.0         38.7            1.6   1.19
3        178.0           39.0         -18.0         -2.4            0.0  -0.46
4        129.0          205.0         -40.0          9.8           -0.3   0.13
..         ...            ...           ...          ...            ...    ...
235      113.0        -1319.0         -46.0         15.4           -0.2  -0.22
236     -183.0         -325.0           1.0        -23.2           -0.1  -0.08
237      227.0        -2363.0         275.0         -3.0            1.5  -0.27
238      102.0          705.0         -41.0         16.4           -0.4  -0.26
239      265.0         3587.0         -36.0          0.1           -0.2  -0.19

[240 rows x 6 columns]

In [24]:
X

     recurring  non_recurring  overtime_pay  normal_hour  overtime_hour  enter
0        240.0        21550.0          37.0         -0.1            0.1   0.15
1       -818.0        -8147.0        -198.0        -40.3           -1.5  -0.21
2        908.0       -15665.0         244.0         38.7            1.6   1.19
3        178.0           39.0         -18.0         -2.4            0.0  -0.46
4        129.0          205.0         -40.0          9.8           -0.3   0.13
..         ...            ...           ...          ...            ...    ...
235      113.0        -1319.0         -46.0         15.4           -0.2  -0.22
236     -183.0         -325.0           1.0        -23.2           -0.1  -0.08
237      227.0        -2363.0         275.0         -3.0            1.5  -0.27
238      102.0          705.0         -41.0         16.4           -0.4  -0.26
239      265.0         3587.0         -36.0          0.1           -0.2  -0.19

[240 rows x 6 columns]

In [25]:
X = sm.add_constant(X)   #增加模型的常數

model0 = sm.OLS(y,X)    #OLS回歸
results0 = model0.fit()

print(results0.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   exit   R-squared:                       0.402
Model:                            OLS   Adj. R-squared:                  0.387
Method:                 Least Squares   F-statistic:                     26.14
Date:                Wed, 12 Oct 2022   Prob (F-statistic):           1.06e-23
Time:                        22:14:18   Log-Likelihood:                 17.023
No. Observations:                 240   AIC:                            -20.05
Df Residuals:                     233   BIC:                             4.319
Df Model:                           6
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.0061      0.015      0.399      0.690      -0.024       0.036
recurring        -0.0002      0.000     -1.552      0.122      -0.000    4.19e-05
non_recurring  8.037e-07   1.52e-06      0.529      0.597   -2.19e-06    3.79e-06
overtime_pay     -0.0006      0.001     -0.760      0.448      -0.002       0.001
normal_hour      -0.0016      0.002     -0.921      0.358      -0.005       0.002
overtime_hour    -0.0044      0.112     -0.039      0.969      -0.225       0.216
enter             0.5283      0.046     11.374      0.000       0.437       0.620
==============================================================================
Omnibus:                        6.870   Durbin-Watson:                   2.184
Prob(Omnibus):                  0.032   Jarque-Bera (JB):                6.623
Skew:                           0.366   Prob(JB):                       0.0365
Kurtosis:                       3.356   Cond. No.                     9.63e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.63e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [26]:
#3 =======================================================================

In [27]:
y = df['exit'] 
X = df.loc[:, df.columns != 'exit']

In [28]:
X

,salary,recurring,non_recurring,overtime_pay,average_hour,normal_hour,overtime_hour,enter,wage_index,recurring_index
0,21790.0,240.0,21550.0,37.0,0.0,-0.1,0.1,0.15,47.88,0.65
1,-8965.0,-818.0,-8147.0,-198.0,-41.8,-40.3,-1.5,-0.21,-19.70,-2.23
2,-14757.0,908.0,-15665.0,244.0,40.3,38.7,1.6,1.19,-32.43,2.48
3,217.0,178.0,39.0,-18.0,-2.4,-2.4,0.0,-0.46,0.48,0.48
4,334.0,129.0,205.0,-40.0,9.5,9.8,-0.3,0.13,0.73,0.35
...,...,...,...,...,...,...,...,...,...,...
235,-1206.0,113.0,-1319.0,-46.0,15.2,15.4,-0.2,-0.22,-2.65,0.31
236,-508.0,-183.0,-325.0,1.0,-23.3,-23.2,-0.1,-0.08,-1.12,-0.50
237,-2136.0,227.0,-2363.0,275.0,-1.5,-3.0,1.5,-0.27,-4.69,0.62
238,807.0,102.0,705.0,-41.0,16.0,16.4,-0.4,-0.26,1.77,0.27
239,3852.0,265.0,3587.0,-36.0,-0.1,0.1,-0.2,-0.19,8.47,0.73

In [29]:
X.drop(X.columns[[0,4,8,9]], axis=1, inplace=True)

C:\Users\James\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [30]:
X

     recurring  non_recurring  overtime_pay  normal_hour  overtime_hour  enter
0        240.0        21550.0          37.0         -0.1            0.1   0.15
1       -818.0        -8147.0        -198.0        -40.3           -1.5  -0.21
2        908.0       -15665.0         244.0         38.7            1.6   1.19
3        178.0           39.0         -18.0         -2.4            0.0  -0.46
4        129.0          205.0         -40.0          9.8           -0.3   0.13
..         ...            ...           ...          ...            ...    ...
235      113.0        -1319.0         -46.0         15.4           -0.2  -0.22
236     -183.0         -325.0           1.0        -23.2           -0.1  -0.08
237      227.0        -2363.0         275.0         -3.0            1.5  -0.27
238      102.0          705.0         -41.0         16.4           -0.4  -0.26
239      265.0         3587.0         -36.0          0.1           -0.2  -0.19

[240 rows x 6 columns]

In [31]:
# 一般來說薪資和上班時間呈正向關係，經驗證
# 加班費 和 加班工時高度相關，故去除加班工時。
# 經常性薪資 和 正常工時高度相關 ， 故去除正常工時。
X.corr()

,recurring,non_recurring,overtime_pay,normal_hour,overtime_hour,enter
recurring,1.000000,-0.106993,0.601037,0.798674,0.674334,0.336949
non_recurring,-0.106993,1.000000,-0.373762,-0.380607,-0.288183,-0.294542
overtime_pay,0.601037,-0.373762,1.000000,0.532446,0.959095,0.270945
normal_hour,0.798674,-0.380607,0.532446,1.000000,0.587405,0.532476
overtime_hour,0.674334,-0.288183,0.959095,0.587405,1.000000,0.299561
enter,0.336949,-0.294542,0.270945,0.532476,0.299561,1.000000

In [32]:
X.drop(X.columns[[3,4]], axis=1, inplace=True)

C:\Users\James\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [33]:
X

     recurring  non_recurring  overtime_pay  enter
0        240.0        21550.0          37.0   0.15
1       -818.0        -8147.0        -198.0  -0.21
2        908.0       -15665.0         244.0   1.19
3        178.0           39.0         -18.0  -0.46
4        129.0          205.0         -40.0   0.13
..         ...            ...           ...    ...
235      113.0        -1319.0         -46.0  -0.22
236     -183.0         -325.0           1.0  -0.08
237      227.0        -2363.0         275.0  -0.27
238      102.0          705.0         -41.0  -0.26
239      265.0         3587.0         -36.0  -0.19

[240 rows x 4 columns]

In [34]:
X = sm.add_constant(X)   #增加模型的常數

model0 = sm.OLS(y,X)    #OLS回歸
results0 = model0.fit()

print(results0.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   exit   R-squared:                       0.400
Model:                            OLS   Adj. R-squared:                  0.390
Method:                 Least Squares   F-statistic:                     39.17
Date:                Wed, 12 Oct 2022   Prob (F-statistic):           4.08e-25
Time:                        22:14:18   Log-Likelihood:                 16.575
No. Observations:                 240   AIC:                            -23.15
Df Residuals:                     235   BIC:                            -5.747
Df Model:                           4
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.0090      0.015      0.604      0.546      -0.020       0.038
recurring        -0.0002   6.41e-05     -3.529      0.001      -0.000   -9.99e-05
non_recurring  1.378e-06   1.31e-06      1.050      0.295   -1.21e-06    3.96e-06
overtime_pay     -0.0006      0.000     -2.207      0.028      -0.001   -6.08e-05
enter             0.5112      0.043     12.024      0.000       0.427       0.595
==============================================================================
Omnibus:                        6.498   Durbin-Watson:                   2.162
Prob(Omnibus):                  0.039   Jarque-Bera (JB):                6.206
Skew:                           0.363   Prob(JB):                       0.0449
Kurtosis:                       3.304   Cond. No.                     3.67e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.67e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [35]:
# drop const 非經常性薪資
X.drop(X.columns[[0,2]], axis=1, inplace=True)

In [36]:
X = sm.add_constant(X)   #增加模型的常數

model0 = sm.OLS(y,X)    #OLS回歸
results0 = model0.fit()

print(results0.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   exit   R-squared:                       0.397
Model:                            OLS   Adj. R-squared:                  0.390
Method:                 Least Squares   F-statistic:                     51.84
Date:                Wed, 12 Oct 2022   Prob (F-statistic):           8.92e-26
Time:                        22:14:18   Log-Likelihood:                 16.014
No. Observations:                 240   AIC:                            -24.03
Df Residuals:                     236   BIC:                            -10.11
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.0086      0.015      0.575      0.566      -0.021       0.038
recurring       -0.0002   6.26e-05     -3.381      0.001      -0.000   -8.83e-05
overtime_pay    -0.0007      0.000     -2.818      0.005      -0.001      -0.000
enter            0.4994      0.041     12.173      0.000       0.419       0.580
==============================================================================
Omnibus:                        5.189   Durbin-Watson:                   2.158
Prob(Omnibus):                  0.075   Jarque-Bera (JB):                4.848
Skew:                           0.328   Prob(JB):                       0.0885
Kurtosis:                       3.236   Cond. No.                         859.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.